# Generated by Django 5.0.3 on 2024-04-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindCater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='restuarant',
            new_name='Restaurant',
        ),
    ]
